CGB_A_INIT EQU $11 ; Accumulator starting value on a Gameboy Color

; LCD
LCD_BASE_CONTROL_BYTE EQU %10010001
LCD_BASE_CONTROL_BYTE_SPRITE EQU %10010011

; Characters
TM_CHARACTER EQU $88

; Interrupts
NO_INTERRUPT EQU 0
VBLANK_INTERRUPT EQU (1 << 0)
LCD_STAT_INTERRUPT EQU (1 << 1)
TIMER_INTERRUPT EQU (1 << 2)
SERIAL_INTERRUPT EQU (1 << 3)
JOYPAD_INTERRUPT EQU (1 << 4)

; Game registers
MAX_TYPED_BUFFER_SIZE EQU $1F

; Cartridge address
SEND_COMMAND_REGISTER   EQU $A000
BUFFER1_STREAM_REGISTER EQU $A001
BUFFER2_FULL_REGISTER   EQU $A002
BUFFER2_STREAM_REGISTER EQU $A003
PORT_LOW_REGISTER       EQU $A004
PORT_HIGH_REGISTER      EQU $A005
IP_B1_REGISTER          EQU $A006
IP_B2_REGISTER          EQU $A007
IP_B3_REGISTER          EQU $A008
IP_B4_REGISTER          EQU $A009
WIFI_CONNECTED_REGISTER EQU $A00A

; Cartridge opcodes
CLEAR_BUFFER1 EQU $00
CLEAR_BUFFER2 EQU $01
SET_SSID      EQU $02
SET_PASSWD    EQU $03
CONNECT_WIFI  EQU $04
ADV_BUFFER2   EQU $05

; DMA
START_DMA EQU $FF46
DMA_DELAY EQU $28
DMA EQU $FF80

; OAM
OAM_SRC_START EQU $DD00

; GBC Palette
BGPI EQU $FF68
BGPD EQU $FF69
OBPI EQU $FF6A
OBPB EQU $FF6B

; SGB Commands
PAL_TRN EQU $59
DATA_SND EQU $79
MLT_REQ EQU $89
CHR_TRN EQU $99
PCT_TRN EQU $A1
MASK_EN EQU $B9