CGB_A_INIT EQU $11 ; A Starting value on a Gameboy Color

; Sound control
DISABLE_CHANNELS_REGISTERS EQU $FF26

; Sound Channel 1
CHANNEL1_LENGTH EQU $FF11
CHANNEL1_VOLUME EQU $FF12
CHANNEL1_LOW_FREQ EQU $FF13
CHANNEL1_HIGH_FREQ EQU $FF14

; Sound Channel 2
CHANNEL2_VOLUME EQU $FF17

; Sound channel 3
CHANNEL3_ON_OFF EQU $FF1A

; Sound channel 4
CHANNEL4_VOLUME EQU $FF21

; LCD
LCD_CONTROL EQU $FF40

; VRAM
VRAM_START EQU $8000
VRAM_BG_START EQU $9800


; Text length
ONLY_GBC_TEXT_LENGTH EQU 51